### ISSUE TITLE
youtube music shortcut (within now playing widget) doesn't work 

### ISSUE THREAD

**Issue by avichou** [Wouter01/MediaMate-Releases#44] opened 2024-02-27 00:02 UTC
youtube music app  isnt opened when clicking on shortcut 

https://github.com/Wouter01/MediaMate-Releases/assets/86660671/d4731858-9e68-441b-aa57-11fc607dc417

OS: sonoma 14.3.1
Device [. M1 Macbook Air]
Version [3.1.2 build 258

youtube music pwa (installed with safari using sonoma "add to dock" feature)

EDIT: doesn't work with chrome PWA either

**Comment by Wouter01** [comment] 2024-02-27 22:01
Does it open Chrome / Safari, or does it just do nothing?

**Comment by avichou** [comment] 2024-02-27 22:11
> Does it open Chrome / Safari, or does it just do nothing?

in the case of safari "saved to dock" app, it doesnt do anything , not even safari 

in the case of chrome pwa, it opens chrome

**Comment by Wouter01** [comment] 2024-02-27 22:17
Thank you for the extra information. I have identified the cause and fixed the issue (for Safari PWA). An update will be released soon.

**Comment by avichou** [comment] 2024-02-27 22:37
> Thank you for the extra information. I have identified the cause and fixed the issue (for Safari PWA). An update will be released soon.

awesome ! should I close the issue ?

**Closed as completed** 2024-02-27 23:36 UTC

**Comment by Wouter01** [comment] 2024-02-28 00:41
The update has been released which fixes this issue!

**Comment by avichou** [comment] 2024-02-28 14:38
> The update has been released which fixes this issue!

seen that ! awesome. I got some more bug reports, you mind me opening issues or you'd rather I wait a bit more and give you some rest ? lol

btw obviously bought the app :)) you're worth it

**Comment by Wouter01** [comment] 2024-02-29 11:25
Sure, feel free to report them in a separate issue!

**Comment by avichou** [comment] 2024-03-04 20:14
> The update has been released which fixes this issue!

should I also re-make a separate issue for shortcut for chrome web apps ?

**Comment by Wouter01** [comment] 2024-03-05 16:51
I have to look in detail for Chrome, but I'm not sure if it's fixable

**Comment by avichou** [comment] 2024-03-21 00:19
> I have to look in detail for Chrome, but I'm not sure if it's fixable

have you any news about this ? sorry to be so annoying ...

im so ashamed for the other issue with play/pause not showing the notch man, my apologies , truly

**Comment by Wouter01** [comment] 2024-03-21 00:22
No problem, don't feel sorry! I have no update about this at the moment. I will look into the issue in the future.

**Comment by avichou** [comment] 2024-03-21 00:25
> No problem, don't feel sorry! I have no update about this at the moment. I will look into the issue in the future.

thank you man ))
