### ISSUE TITLE
Screen brightness HUD not showing when changing

### ISSUE THREAD

**Issue by victordegnbol** [Wouter01/MediaMate-Releases#41] opened 2024-02-26 17:03 UTC
**Describe the bug**

**To Reproduce**
1. Open MediaMate
2. Change brightness up and/or down and watch for the HUD
3. No HUD is shown, but brightness still changes as normally

**Expected behavior**
I expect the HUD to show, like it does for the volume and keyboard brightness HUDs

**Please complete the following information:**
 - OS: [Sonoma 14.3.1]
 - Device [MacBook Pro M3 Pro]
 - Version [3.1.2 build 258]

**In case of a keyboard-related issue, please specify the used keyboard**:
- Layout: [Nordic QWERTY]
- non-touchbar

**Additional context**
Worked in the previous version

**Comment by Wouter01** [comment] 2024-02-27 22:07
Thank you for the information. What event controller mode are you using? (mediamate settings -> general -> event controller mode)

**Comment by victordegnbol** [comment] 2024-02-28 06:23
I was using BetterDisplay (with BetterDisplay opened, of course).

I see that the brightness HUD works when changing to "Keyboard" or "System". It's only BetterDisplay that doesn't work. For me this is not the biggest deal, because I have no problem just using Vivid

Thank you for helping me debug and fix the issue :)

**Comment by Wouter01** [comment] 2024-02-28 10:37
BetterDisplay mode should be pretty reliable, and its often just some misconfiguration that's causing it not to work.

Could you check that:
- You are on the latest BetterDisplay version
- You have a PRO license activated for BetterDisplay
MediaMate will also auto-adjust some settings in BetterDisplay, but this may have failed. Could you check that in BetterDisplay settings:
- Application -> Dispatch OSD notifications is enabled
- Keyboard -> Show brightness, volume, mute OSD is off
- Keyboard -> Show custom OSD icons is off

If the issue is fixed for you, feel free to close the issue.

**Comment by victordegnbol** [comment] 2024-03-04 16:44
Thank you it is resolved now :)

**Closed as completed** 2024-03-04 16:43 UTC
